# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'RSisterMusicPlayer' do

pod 'AFNetworking'
pod 'Masonry'
pod 'FMDB'
pod 'YapDatabase'
pod 'SDWebImage'

end

target 'RSisterMusicPlayerTests' do

end

target 'RSisterMusicPlayerUITests' do

end

